### ISSUE TITLE
Order Deletion Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#16]
The application currently lacks the functionality to delete orders. This feature is important for users and admins to manage orders, especially in cases where an order is mistakenly placed or needs to be canceled for any reason. Users should be able to delete orders from their order history.

**Steps to Reproduce**
1. Place an order through the application.
2. Navigate to the order history or view order details.
3. Observe that there is no option to delete or cancel an order.
4. Attempt to delete the order from the user interface, but no option is available.

**Expected Behavior**
- Order Deletion:
1. Users should have the ability to delete an order from their order history.
2. Shop owner should be able to delete orders from their dashboard.
3. The deletion process should trigger a confirmation dialog.

- Order History Update:
1. After deletion, the order should be removed from the user’s order history page.

**Actual Behavior**
- The application currently does not provide any option to delete or cancel orders from the user profile or admin dashboard.
- Users cannot modify their order history once an order is placed, and canceled orders are not tracked properly.

Environment:
- Windows 11.

![Screenshot (939)](https://github.com/user-attachments/assets/ad254491-a1c5-4ebe-89fa-f1294877830a)

**Comment by Jouriab** [comment]
As a university administrator, I want to set operational guidelines for restaurants on the platform, including opening hours and order limits, so that food services align with campus policies and schedules.

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to have the ability to limit the number of orders during peak times so that I can manage my kitchen capacity and ensure timely service.

**Comment by RahafDaas** [comment]
This issue has been resolved by creating the order history page with delete buttons so that users can delete orders. Also, for the shop owner, they also now have a delete button to delete an order. 

Steps to ensure successful resolution of issue for users:
1. Log in.
2. Navigate to order history.
3. Delete an order.
4. Alert is displayed.
5. The order is deleted. 

**Screenshots for successful resolution of issue for users:**
![Screenshot (958)](https://github.com/user-attachments/assets/6e5e7e32-0bdb-46ba-8ee2-527a6109c0b5)
![Screenshot (961)](https://github.com/user-attachments/assets/d49590b8-d950-4137-9e5e-6088345b875e)
![Screenshot (962)](https://github.com/user-attachments/assets/6d42cf16-6665-4224-8e85-a6244b78f80d)

Steps to ensure successful resolution of the issue for Shop owners:
1. Log in.
2. Delete an order.
3. Alert is displayed.
4. The order is deleted.

**Screenshots for successful resolution of issue for shop owners:**
![Screenshot (963)](https://github.com/user-attachments/assets/421c43d3-2c47-4e7b-88be-dec6e9aa5d23)
![Screenshot (964)](https://github.com/user-attachments/assets/8c13d9c0-183c-4da0-ac32-102311bf21b7)
