### ISSUE TITLE
Credential Verification for Users Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#3]

**Comment by Jouriab** [comment]
As a student or faculty member, I want to log in to the website using my PSU email and password so that I can securely access the platform.

**Comment by Jouriab** [comment]
As a university administrator, I want to manage student and staff access to the platform so that only authorized users can place orders and interact with the service.

**Comment by RahafDaas** [comment]
The Credential Verification feature is an essential feature for providing privacy, security, and availability. This issue has been resolved by providing error messages when login fails, wrong patterns of passwords, and wrong PSU emails. This issue was Encountered and resolved for all types of users like admin, shopowner, and normal users. 

**Steps to ensure successful resolving of the issue:**
1. Run the website.
2. Enter invalid credentials in Log In.
3. An error message is displayed. 

![image](https://github.com/user-attachments/assets/8732af48-2c3b-43bf-a50a-b79853422c5c)
![image](https://github.com/user-attachments/assets/78cbde37-a206-4966-9a72-9c50149ed101)
![image](https://github.com/user-attachments/assets/32170125-9a9b-4df5-9280-be36c65b68cd)
