### ISSUE TITLE
Account Editing Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#4]

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to create and manage my shop's profile on the platform so that I can provide accurate information about my business to students and staff.

**Comment by RahafDaas** [comment]
This is very critical since the account editing feature was one of the prioritized features. the issue has been resolved successfully by adding button div and i tag for the account figure. 

**Steps to ensure successful Account Editing:**
1. Log in. 
2. Navigate to user home page.
3. Allocate the Account Editing icon and press it.
4. The Account Edit page is displayed. 
5. Modify data.
6. Data is Updated. 

![Screenshot (931)](https://github.com/user-attachments/assets/a2df7567-03cf-4229-8ab3-b9fd16fd0f1d)
