### ISSUE TITLE
Missing Adding and Viewing Menu Items Functionality

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#6]

**Comment by Jouriab** [comment]
As a student or faculty member, I want to view the menu of the selected restaurant or coffee shop after choosing it so that I can explore its offerings.

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to upload and update my menu on the platform so that students and staff can see the latest food and drink options available.

**Comment by RahafDaas** [comment]
This feature acts as one of the core functionalities of the application since, without menu items, an order can not be placed. Therefore, the issue has been resolved by creating a collection on MongoDB and adding routes in server.js to handle the data passed and store them in the Database. Also, appropriate HTML and CSS components are added to the required pages. 

**Steps to ensure successful issue resolution in the shop owner path:**
1. The shop owner logs in.
2. Find the add menu items button and press it.
3. Proceed to add menu items page.
4. Add a menu item.
5. The menu item is displayed.

Screenshots of resolved issues in shop owner:
![Screenshot (941)](https://github.com/user-attachments/assets/0dd10ab2-8e57-48fc-bea5-30c7778dc698)
![Screenshot (942)](https://github.com/user-attachments/assets/7e9596c0-c15e-4b8b-9709-9b1cfb340850)
![Screenshot (943)](https://github.com/user-attachments/assets/8a8cd773-298e-4bab-a683-d163e57b1456)
![Screenshot (944)](https://github.com/user-attachments/assets/7593388c-7414-4c20-9f92-81811d9b7bbb)

**Steps to ensure successful issue resolution in the user path:**
1. The user logs in.
2. Find the fetched Restaurants from the Database.
3. Click on Selu Cafe to go to the menu of Selu.
4. Menu items are displayed. 

Screenshots of resolved issues in user:
![Screenshot (945)](https://github.com/user-attachments/assets/63a7f490-94c8-4656-9cc1-67f11f4484a9)
![Screenshot (946)](https://github.com/user-attachments/assets/bbe55191-0eba-41b4-83f0-abd8a4cabbad)
