### ISSUE TITLE
Menu Sorting Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#7]
The application currently lacks the ability to sort menu items based on different criteria (e.g., price, name, category). This feature is important to enhance user experience, especially when dealing with large or varied menus.

**Steps to Reproduce**
1. Open the menu page as a user.
2. Observe the list of menu items displayed.
3. Attempt to sort the menu items by different criteria (e.g., price, name).
4. Notice that there is no sorting option available.

**Expected Behavior**
- Users should be able to sort the menu by two attributes:
Price: Sort in ascending or descending order.
Name: Sort alphabetically (A-Z or Z-A).

**Actual Behavior**
- No sorting options are available on the menu page.
- Users are forced to browse through the entire list without any way to filter or reorder the items.

Environment: 
- Windows 11.

![image](https://github.com/user-attachments/assets/95f9a980-14e6-4efc-aa8e-5d68d037a7c8)

**Comment by Jouriab** [comment]
As a student or faculty member, I want to see the best offers from restaurants and coffee shops appear first on the homepage so that I can take advantage of the latest deals.

**Comment by Jouriab** [comment]
As a student or faculty member, I want to see the item's description, including the name, price, available offers, and nutritional information, so that I can make informed choices about my order.

**Comment by RahafDaas** [comment]
This issue is important to improve the user experience in the website. Since the main goal of the application is to improve user experience, this issue has been resolved successfully by adding sorting functionality in the HTML page of menu.

**Steps to ensure successful resolution of the issue:**
1. Log in.
2. Click on any restaurant.
3. Sort the menu using the drop-down menu or Search for an item. 

Screenshots of the resolution:
![Screenshot (948)](https://github.com/user-attachments/assets/7a294f98-89d7-408e-aedd-f48f7e430b48)
![Screenshot (949)](https://github.com/user-attachments/assets/7fcea1d7-01bf-4462-8849-887e00f31c67)
