### ISSUE TITLE
Pick-Up Scheduling Feature Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#9]
The application currently lacks the ability for users to schedule pick-up times for orders. This feature is essential for businesses that offer pick-up services, allowing customers to select a convenient time for collection, improving customer experience and operational efficiency.

**Steps to Reproduce**
1. Navigate to the cart page.
2. Attempt to select a time for pick-up.
3. Notice that there is no option to schedule a pick-up time.

**Expected Behavior**
1. Users should be able to select a date and time for their pick-up from an available time slot.
2. Allow users to choose a specific time within the store’s working hours.

**Actual Behavior**
- No pick-up scheduling options are available.
- Users are not prompted to choose a pick-up time, which leads to potential delays or confusion.

Environment:
- Windows 11.

![image](https://github.com/user-attachments/assets/509e9867-212c-4e04-80bf-e6a4ee6a831f)

**Comment by Jouriab** [comment]
As a user (student or faculty member), I want to schedule my order pickup time so that I can grab my food at a convenient time between classes or meetings.

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to set estimated preparation and pickup times for orders so that customers know when to expect their food.

**Comment by RahafDaas** [comment]
This issue has been solved in user home page since it is essential to the functionality of the website. Therefore, a div and selection button are added to the cart page for users to choose their preferred time to pick up. Also the pick up times are stored in the database in orders collection, if no time chosen an error message is displayed. 

Steps to ensure successful resolution of issue:
1. Log in.
2. Choose a Restaurant.
3. Add menu item.
4. Go to cart.
5. Choose a pick up time. 
6. if no time chosen error message is displayed. 

![image](https://github.com/user-attachments/assets/92578b7c-f215-48c3-a4bc-712cfc830488)
